import Link from "next/link";
import { HubHeader, HubPage, HubTabs, MetricCards } from "./hub-layout";
import { OperationRecords } from "./operation-records";
const tabs = [{ id: "contacts", label: "联系人" }, { id: "people", label: "人物情报" }, { id: "institutions", label: "机构" }, { id: "experts", label: "专家" }];
export function ResourcesCenter({ initialView, realSummary, realPeople = [], realInstitutions = [] }: {
  initialView: string;
  realSummary: { people: number; institutions: number; experts: number; contacts?: number; followUps?: number };
  realPeople?: Array<{ id: string; name: string; organization: string | null; title: string | null; track: string | null; companyRoles?: Array<{ companyName: string; role: string }>; previousStartups?: string[]; technicalEvidenceCount?: number; careerEvents24m?: number; education?: string[]; employment?: string[]; technicalBackground?: string | null; publications?: string[]; patents?: string[]; homepage?: string | null; reports?: string[]; publicContacts?: Array<{ type: string; value: string; sourceUrl: string; verifiedAt: string }> }>;
  realInstitutions?: Array<{ id: string; name: string; headquarters: string | null; tracks: string[]; portfolioCount: number }>;
}) {
  const active = tabs.some((tab) => tab.id === initialView) ? initialView : "contacts";
  return <HubPage><HubHeader eyebrow="Relationship intelligence" title="资源中心" description="管理联系人、人物、机构和专家。" source="real" /><HubTabs basePath="/resources" tabs={tabs} active={active} />
    <MetricCards items={[{ label: "关键人物", value: realSummary.people, detail: "人物库记录" }, { label: "机构", value: realSummary.institutions, detail: `${realSummary.institutions} 家机构` }, { label: "专家", value: realSummary.experts, detail: "工作空间已登记专家" }, { label: "7 日待跟进", value: realSummary.followUps ?? 0, detail: "联系人及专家跟进日期" }]} />
    {active === "contacts" || active === "experts" ? <OperationRecords key={active} kind={active === "experts" ? "expert" : "contact"} /> : active === "institutions" ? <section className="grid gap-3 sm:grid-cols-2">{realInstitutions.map((item) => <Link key={item.id} href={`/investors/${encodeURIComponent(item.id)}`} className="rounded-xl border bg-card p-4 hover:bg-muted"><h2 className="font-semibold">{item.name}</h2><p className="mt-2 text-sm text-muted-foreground">{item.headquarters ?? "地区待补充"} · {item.tracks.join(" / ") || "赛道待补充"} · {item.portfolioCount} 次出手</p><span className="mt-3 block text-sm text-primary">查看机构详情</span></Link>)}{realInstitutions.length === 0 && <p>暂无机构记录</p>}</section> : <section className="space-y-3"><div className="grid gap-3 sm:grid-cols-2">{realPeople.map((item) => <article key={item.id} id={`person-${item.id}`} className="scroll-mt-24 rounded-xl border bg-card p-4"><h2 className="font-semibold">{item.name}</h2><p className="mt-2 text-sm text-muted-foreground">{item.organization ?? "当前任职待核验"} · {item.title ?? "职务待补充"} · {item.track ?? "领域待补充"}</p><details className="mt-3 text-sm"><summary className="min-h-11 cursor-pointer py-3 font-medium text-primary">查看人物情报</summary><div className="grid gap-3 border-t pt-3 text-sm"><p>技术证据：{item.technicalEvidenceCount ?? 0} 条 · 职业事件：{item.careerEvents24m ?? 0} 条</p><PersonFacts label="教育背景" values={item.education} /><PersonFacts label="工作履历" values={item.employment} />{item.technicalBackground && <p><strong>技术背景：</strong>{item.technicalBackground}</p>}<PersonFacts label="论文" values={item.publications} /><PersonFacts label="专利" values={item.patents} />{item.reports?.length ? <div><strong>相关报道</strong><ul className="mt-1 list-disc space-y-1 pl-5">{item.reports.map((report) => <li key={report}><a href={report} target="_blank" rel="noreferrer" className="break-all text-primary hover:underline">{report}</a></li>)}</ul></div> : null}{item.companyRoles?.map((role, index) => <p key={index}>{role.companyName} · {role.role}</p>)}{item.previousStartups?.length ? <p>过往创业：{item.previousStartups.join("、")}</p> : <p>暂无已登记创业经历</p>}{item.homepage && <a href={item.homepage} target="_blank" rel="noreferrer" className="text-primary hover:underline">个人主页</a>}{item.publicContacts?.map((contact) => <p key={`${contact.type}:${contact.value}`}><strong>公开工作联系方式：</strong><a href={contact.sourceUrl} target="_blank" rel="noreferrer" className="text-primary hover:underline">{contact.value}</a></p>)}</div></details></article>)}{realPeople.length === 0 && <p>暂无人物记录</p>}</div></section>}
  </HubPage>;
}

function PersonFacts({ label, values = [] }: { label: string; values?: string[] }) { return values.length ? <div><strong>{label}：</strong><ul className="mt-1 list-disc space-y-1 pl-5 text-muted-foreground">{values.map((value) => <li key={value}>{value}</li>)}</ul></div> : null; }
