import { randomUUID } from "node:crypto";
import { appendFileSync, writeFileSync } from "node:fs";
import { expect, test, type Page } from "@playwright/test";
import { readAuthFixture } from "./fixtures";
import { login } from "./login";
const origin = "http://127.0.0.1:3107";
const step = (value: string) => appendFileSync("/tmp/vc-activity-discussion-steps.log", `${value}\n`, { mode: 0o600 });
test("authors and approvers hold repeated threaded discussions with files before and after approval", async ({ browser }) => {
  writeFileSync("/tmp/vc-activity-discussion-steps.log", "start\n", { mode: 0o600 });
  const { admin, member } = readAuthFixture();
  const creator = await browser.newContext({ baseURL: origin }), recipient = await browser.newContext({ baseURL: origin }), anonymous = await browser.newContext({ baseURL: origin });
  try {
    const author = await creator.newPage(); await login(author, admin); author.setDefaultTimeout(10_000);
    const reviewer = await recipient.newPage(); await login(reviewer, member); reviewer.setDefaultTimeout(10_000);
    const projectId = "project-qiongxin";
    const sourceProject = (await (await creator.request.get(`/api/v1/projects/${projectId}`)).json()).data;
    const uploaded = await creator.request.post(`/api/v1/projects/${projectId}/documents`, { headers: { origin, "idempotency-key": randomUUID() }, multipart: { expectedVersion: String(sourceProject.version), externalPolicy: "local_only", file: { name: "批复项目底稿.txt", mimeType: "text/plain", buffer: Buffer.from("批复引用的项目原件正文") } } });
    expect(uploaded.status()).toBe(201);
    const created = await creator.request.post("/api/v1/activity", { headers: { origin, "idempotency-key": randomUUID() }, data: { kind: "approval", title: "E2E多轮批复讨论", participantIds: [member.teamUserId], dueAt: "2026-10-01T10:00:00.000Z" } });
    expect(created.ok()).toBe(true); const activity = (await created.json()).data;
    const card = (page: Page) => page.getByRole("article").filter({ has: page.getByRole("button", { name: "事项概览：E2E多轮批复讨论", exact: true }) });
    await author.goto(`/approvals?activity=${activity.id}`); await card(author).getByRole("button", { name: "审核 / 批注", exact: true }).click();
    await card(author).getByLabel("批注内容", { exact: true }).fill("请审核人核对测试记录。");
    const [firstResponse] = await Promise.all([author.waitForResponse(response => response.request().method() === "POST" && new URL(response.url()).pathname === `/api/v1/activity/${activity.id}/comments`), card(author).getByRole("button", { name: "发表批注", exact: true }).click()]);
    expect(firstResponse.status()).toBe(201); const first = (await firstResponse.json()).data; step("author first comment saved");
    await reviewer.goto(`/approvals?activity=${activity.id}`); await card(reviewer).getByRole("button", { name: "审核 / 批注", exact: true }).click();
    await expect(card(reviewer).getByText("请审核人核对测试记录。", { exact: true })).toBeVisible();
    await card(reviewer).getByRole("button", { name: `回复 ${admin.name}的批注`, exact: true }).click();
    await card(reviewer).getByLabel("批注内容", { exact: true }).fill("测试已核对，补充 @批复项目底稿");
    await card(reviewer).getByRole("button", { name: /批复项目底稿.txt/ }).click();
    await card(reviewer).getByLabel("附上文件", { exact: true }).setInputFiles({ name: "复核记录.txt", mimeType: "text/plain", buffer: Buffer.from("复核人上传的完整记录") });
    const [replyResponse] = await Promise.all([reviewer.waitForResponse(response => response.request().method() === "POST" && new URL(response.url()).pathname === `/api/v1/activity/${activity.id}/comments`), card(reviewer).getByRole("button", { name: "发表回复", exact: true }).click()]);
    expect(replyResponse.status()).toBe(201); const reply = (await replyResponse.json()).data;
    expect(reply.parentId).toBe(first.id); expect(reply.documents).toHaveLength(2); step("reviewer mixed attachments saved");
    await card(reviewer).getByRole("button", { name: "批准", exact: true }).click();
    await expect(card(reviewer).getByRole("button", { name: "批准", exact: true })).toHaveCount(0);
    await author.reload(); await card(author).getByRole("button", { name: "审核 / 批注", exact: true }).click();
    await card(author).getByRole("button", { name: "预览 复核记录.txt", exact: true }).click();
    const localPreview = author.getByRole("dialog", { name: "复核记录.txt", exact: true });
    await expect(localPreview.getByText("复核人上传的完整记录", { exact: true })).toBeVisible();
    await localPreview.getByRole("button", { name: "关闭批注附件预览", exact: true }).click();
    await expect(localPreview).toHaveCount(0);
    await card(author).getByRole("button", { name: "预览 批复项目底稿.txt", exact: true }).click();
    const sourcePreview = author.getByRole("dialog", { name: "批复项目底稿.txt", exact: true });
    await expect(sourcePreview.getByText("批复引用的项目原件正文", { exact: true })).toBeVisible();
    await sourcePreview.getByRole("button", { name: "关闭批注附件预览", exact: true }).click();
    await expect(sourcePreview).toHaveCount(0);
    const url = (await card(author).getByRole("link", { name: "下载 复核记录.txt", exact: true }).getAttribute("href"))!;
    expect(await (await creator.request.get(url)).text()).toBe("复核人上传的完整记录");
    expect(await (await recipient.request.get(url)).text()).toBe("复核人上传的完整记录"); expect((await anonymous.request.get(url)).status()).toBe(401);
    await card(author).getByRole("button", { name: `回复 ${member.name}的批注`, exact: true }).click();
    await card(author).getByLabel("批注内容", { exact: true }).fill("已收到批准后的补充材料。");
    await card(author).getByRole("button", { name: "发表回复", exact: true }).click();
    await expect(card(author).getByText("已收到批准后的补充材料。", { exact: true })).toBeVisible();
    await reviewer.reload(); await card(reviewer).getByRole("button", { name: "审核 / 批注", exact: true }).click();
    await expect(card(reviewer).getByText("已收到批准后的补充材料。", { exact: true })).toBeVisible();
    const persisted = (await (await creator.request.get("/api/v1/activity")).json()).data.find((item: { id: string }) => item.id === activity.id);
    expect(persisted.version).toBe(2); expect(persisted.responses[0].action).toBe("approved"); step("post-approval discussion and formal status verified");
    await author.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => author.locator("#main-content").evaluate(element => getComputedStyle(element).paddingLeft)).toBe("0px");
    await card(author).getByLabel("批注内容", { exact: true }).scrollIntoViewIfNeeded();
    expect(await author.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
    await author.screenshot({ path: "/tmp/vc-activity-discussion-mobile.png", animations: "disabled" });
  } finally { await creator.close(); await recipient.close(); await anonymous.close(); }
});
