import sharp from "sharp";
import { randomUUID } from "node:crypto";
import { expect, test, type APIRequestContext, type Page } from "@playwright/test";
import { readAuthFixture } from "./fixtures";
import { login } from "./login";
const origin = "http://127.0.0.1:3107";
async function post(api: APIRequestContext, url: string, data: unknown) {
  const response = await api.post(url, { headers: { origin, "idempotency-key": randomUUID() }, data });
  expect(response.ok(), url).toBe(true);return (await response.json()).data;
}

test("text-first threaded comments support mentions, photos, deletion and preserve replies", async ({ browser }) => {
  const { admin, member } = readAuthFixture();
  const authorContext = await browser.newContext({ baseURL: origin }), adminContext = await browser.newContext({ baseURL: origin });
  try {
    authorContext.setDefaultTimeout(15_000);adminContext.setDefaultTimeout(15_000);
    const author = await authorContext.newPage(), manager = await adminContext.newPage();
    await login(author, member);await login(manager, admin);
    const activity = await post(authorContext.request, "/api/v1/activity", { kind: "approval", title: "评论区删除验收", description: "展开后处理审批与讨论", participantIds: [admin.teamUserId] });
    const card = (page: Page) => page.getByRole("article").filter({ has: page.getByRole("button", { name: "事项概览：评论区删除验收", exact: true }) });
    await author.goto("/approvals");
    await expect(card(author).getByRole("button", { name: "审核 / 批注", exact: true })).toHaveCount(0);
    await expect(card(author).getByText("展开后处理审批与讨论", { exact: true })).toBeVisible();
    await card(author).getByRole("button", { name: "事项概览：评论区删除验收", exact: true }).click();
    await card(author).getByRole("button", { name: "审核 / 批注", exact: true }).click();
    await card(author).getByLabel("批注内容", { exact: true }).fill("需要保留的回复上下文 ");
    await card(author).getByRole("button", { name: "@人员", exact: true }).click();
    await card(author).getByRole("group", { name: "可提醒的人员" }).getByRole("button", { name: admin.name, exact: true }).click();
    await expect(card(author).getByLabel("批注内容", { exact: true })).toHaveValue(new RegExp(`@${admin.name}`));
    await card(author).getByLabel("附上文件", { exact: true }).setInputFiles({ name: "讨论照片.png", mimeType: "image/png", buffer: await sharp({ create: { width: 20, height: 20, channels: 4, background: "#779977" } }).png().toBuffer() });
    const [createdResponse] = await Promise.all([author.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith(`/activity/${activity.id}/comments`)), card(author).getByRole("button", { name: "发表批注", exact: true }).click()]);
    expect(createdResponse.status()).toBe(201);const parent = (await createdResponse.json()).data;
    const photoUrl = await card(author).getByRole("link", { name: "下载 讨论照片.png", exact: true }).getAttribute("href");
    await card(author).getByRole("button", { name: "预览 讨论照片.png", exact: true }).click();
    await expect(author.getByRole("dialog", { name: "讨论照片.png", exact: true }).getByRole("img", { name: "讨论照片.png", exact: true })).toBeVisible();
    await author.getByRole("button", { name: "关闭批注附件预览", exact: true }).click();
    await manager.goto(`/approvals?activity=${activity.id}`);
    await card(manager).getByRole("button", { name: "审核 / 批注", exact: true }).click();
    await card(manager).getByRole("button", { name: `回复 ${member.name}的批注`, exact: true }).click();
    const parentRow = card(manager).locator(`[id="comment-${parent.id}"]`);
    await expect(parentRow.getByLabel("批注内容", { exact: true })).toBeVisible();
    await parentRow.getByLabel("批注内容", { exact: true }).fill("这条回复需要保留");
    await parentRow.getByRole("button", { name: "发表回复", exact: true }).click();
    await expect(card(manager).getByText("这条回复需要保留", { exact: true })).toBeVisible();
    await card(author).getByRole("button", { name: "刷新批注", exact: true }).click();
    await expect(card(author).getByRole("button", { name: "删除评论", exact: true })).toHaveCount(1);
    await card(author).getByRole("button", { name: "删除评论", exact: true }).click();
    await card(author).getByRole("button", { name: "确认删除", exact: true }).click();
    await expect(card(author).getByText("该评论已删除", { exact: true })).toBeVisible();
    await expect(card(author).getByText("这条回复需要保留", { exact: true })).toBeVisible();
    await expect(card(author).getByRole("button", { name: "预览 讨论照片.png", exact: true })).toHaveCount(0);
    expect((await authorContext.request.get(photoUrl!)).status()).toBe(404);
    await author.reload();await card(author).getByRole("button", { name: "事项概览：评论区删除验收", exact: true }).click();await card(author).getByRole("button", { name: "审核 / 批注", exact: true }).click();
    await expect(card(author).getByText("该评论已删除", { exact: true })).toBeVisible();
    const milestone = await post(adminContext.request, "/api/v1/projects/project-qiongxin/milestones", { title: "删除批注验收节点", stage: "dd" });
    await post(authorContext.request, "/api/v1/projects/project-qiongxin/comments", { body: "待删除的项目意见", milestoneId: milestone.id });
    await author.goto("/projects/project-qiongxin");await author.getByRole("tab", { name: "项目流程", exact: true }).click();
    const node = author.getByRole("article").filter({ has: author.getByRole("heading", { name: "删除批注验收节点", exact: true }) });
    await expect(node.getByText("待删除的项目意见", { exact: true })).toBeVisible();
    await node.getByRole("button", { name: "删除评论", exact: true }).click();await node.getByRole("button", { name: "确认删除", exact: true }).click();
    await expect(node.getByText("该评论已删除", { exact: true })).toBeVisible();
    const source = (await (await adminContext.request.get("/api/v1/projects/project-qiongxin")).json()).data;
    const upload = await adminContext.request.post("/api/v1/projects/project-qiongxin/documents", { headers: { origin, "idempotency-key": randomUUID() }, multipart: { expectedVersion: String(source.version), externalPolicy: "local_only", file: { name: "删除批注资料.txt", mimeType: "text/plain", buffer: Buffer.from("需要保留的原文件") } } });
    expect(upload.status()).toBe(201);const document = (await upload.json()).data;
    const annotationUrl = `/api/v1/projects/project-qiongxin/documents/${document.id}/annotations`;
    await post(authorContext.request, annotationUrl, { action: "comment", content: "可以删除的资料意见", parentId: null });
    await post(adminContext.request, annotationUrl, { action: "approve", content: "正式审核保留", parentId: null });
    await author.reload();await author.getByRole("tab", { name: "资料与审批", exact: true }).click();
    await author.getByRole("button", { name: "审核 / 批注 删除批注资料.txt", exact: true }).click();
    const note = author.getByRole("article", { name: "批注：可以删除的资料意见", exact: true });
    await note.getByRole("button", { name: "删除评论", exact: true }).click();await note.getByRole("button", { name: "确认删除", exact: true }).click();
    await expect(author.getByRole("dialog", { name: "删除批注资料.txt", exact: true }).getByText("该批注已删除", { exact: true })).toBeVisible();
    await expect(author.getByText("正式审核保留", { exact: true })).toBeVisible();
    await expect(author.getByText("资料已通过", { exact: true })).toBeVisible();
    await author.screenshot({ path: "/tmp/vc-comment-feed-desktop.png", fullPage: true });
    await author.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => author.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await author.screenshot({ path: "/tmp/vc-comment-feed-mobile.png", fullPage: true });
  } finally { await authorContext.close();await adminContext.close(); }
});
