"use client";
import { useState } from "react";
import { Button, InlineNotification, Tag } from "@/components/ui/legacy";

interface Entry { id: string; projectId: string | null; track: string | null; type: string; title: string; content: string; sourceType: string; sourceId: string; status: string; version: number; createdAt: string; }
export function KnowledgeEntries({ initialEntries }: { initialEntries: Entry[] }) {
  const [entries, setEntries] = useState(initialEntries); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function review(entry: Entry, decision: "approve" | "reject") { setBusy(entry.id); setError(null); try { const response = await fetch(`/api/v1/knowledge/${entry.id}/review`, { method: "PATCH", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ decision, expectedVersion: entry.version, note: decision === "approve" ? "投资经理审核通过" : "信息不足，暂不入库" }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "审核失败。"); setEntries((current) => current.map((item) => item.id === entry.id ? { ...item, status: payload.data.status, version: payload.data.version } : item)); } catch (cause) { setError(cause instanceof Error ? cause.message : "审核失败。"); } finally { setBusy(null); } }
  return <>{error && <InlineNotification kind="error" lowContrast title="知识审核未完成" subtitle={error} hideCloseButton />}{entries.length === 0 ? <div className="empty-state"><strong>暂无项目沉淀</strong><p>项目资料或研究报告分析完成后，带来源的知识草稿会出现在这里。</p></div> : <div className="knowledge-entry-list">{entries.map((entry) => <article key={entry.id}><header><div><Tag type={entry.status === "approved" ? "green" : entry.status === "rejected" ? "gray" : "purple"}>{entry.status === "approved" ? "已入库" : entry.status === "rejected" ? "已拒绝" : "待审核"}</Tag>{entry.track && <Tag type="blue">{entry.track}</Tag>}</div><span>{entry.type}</span></header><h3>{entry.title}</h3><p>{entry.content}</p><small>来源：{entry.sourceType} / {entry.sourceId}</small>{entry.status === "draft" && <footer><Button kind="danger--tertiary" size="sm" disabled={busy !== null} onClick={() => review(entry, "reject")}>拒绝</Button><Button size="sm" disabled={busy !== null} onClick={() => review(entry, "approve")}>{busy === entry.id ? "处理中..." : "审核入库"}</Button></footer>}</article>)}</div>}</>;
}
